; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I

define i32 @leaf(i32 %x) {
; RV32I-LABEL: leaf:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
  ret i32 %x
}

declare void @foo()

define void @non_leaf() {
; RV32I-LABEL: non_leaf:
; RV32I:       # %bb.0:
; RV32I-NEXT:    pac a0, ra, sp
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    .cfi_def_cfa_offset 16
; RV32I-NEXT:    sw ra, 12(sp)
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    call foo
; RV32I-NEXT:    lw ra, 12(sp)
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    aut ra, ra, zero, sp
; RV32I-NEXT:    ret
  call void @foo()
  ret void
}
