; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I

define i32 @leaf(i32 %x) {
; RV32I-LABEL: leaf:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
  ret i32 %x
}

define i32 @leaf_sign_none(i32 %x) "sign-return-address"="none" {
; RV32I-LABEL: leaf_sign_none:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
  ret i32 %x
}

define i32 @leaf_sign_non_leaf(i32 %x) "sign-return-address"="non-leaf" {
; RV32I-LABEL: leaf_sign_non_leaf:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
  ret i32 %x
}

define i32 @leaf_sign_all(i32 %x) "sign-return-address"="all" {
; RV32I-LABEL: leaf_sign_all:
; RV32I:       # %bb.0:
; RV32I-NEXT:    aut ra, ra, t6, sp
; RV32I-NEXT:    ret
  ret i32 %x
}

declare i32 @foo(i32)

define i32 @non_leaf_sign_all(i32 %x) "sign-return-address"="all" {
; RV32I-LABEL: non_leaf_sign_all:
; RV32I:       # %bb.0:
; RV32I-NEXT:    pac t6, ra, sp
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    .cfi_def_cfa_offset 16
; RV32I-NEXT:    sw ra, 12(sp)
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    call foo
; RV32I-NEXT:    lw ra, 12(sp)
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    aut ra, ra, t6, sp
; RV32I-NEXT:    ret
  %call = call i32 @foo(i32 %x)
  ret i32 %call
}

define i32 @non_leaf_sign_non_leaf(i32 %x) "sign-return-address"="non-leaf" {
; RV32I-LABEL: non_leaf_sign_non_leaf:
; RV32I:       # %bb.0:
; RV32I-NEXT:    pac t6, ra, sp
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    .cfi_def_cfa_offset 16
; RV32I-NEXT:    sw ra, 12(sp)
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    call foo
; RV32I-NEXT:    lw ra, 12(sp)
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    aut ra, ra, t6, sp
; RV32I-NEXT:    ret
  %call = call i32 @foo(i32 %x)
  ret i32 %call
}
